name: Add ESXi Bundle ZIP File Without Lfs
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        default: 'ESXi670'

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Download Big ZIP
        shell: powershell
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile('${{ secrets.EXTERNAL_DOWNLOAD_URL }}','${{ github.event.inputs.tag }}.zip')
          ls
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN }}
          name: ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            ${{ github.event.inputs.tag }}.zip
