name: Auto Generate EXSi ISO
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true
        default: 'ESXi670-net55-r8168'
      driver:
        description: 'Driver Name'
        required: true
        default: 'net55-r8168'

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Big ZIP
        shell: powershell
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile('${{ secrets.DOWNLOAD_URL }}','ESXi670-201912001.zip')
          ls
      - name: Download Script
        shell: powershell
        run: |
          $client = new-object System.Net.WebClient
          $client.DownloadFile('https://github.com/VFrontDe/ESXi-Customizer-PS/archive/refs/tags/2.8.1.zip','ESXi-Customizer-PS.zip')
          Expand-Archive -Path ESXi-Customizer-PS.zip -DestinationPath ./
          cd ESXi-Customizer-PS-2.8.1
          $env:WORK_DIR=$PWD
          $env:WORK_DIR
          echo "WORK_DIR=$env:WORK_DIR" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install PowerCLI
        shell: powershell
        run: Install-Module -Name VMware.PowerCLI -AcceptLicense -Force

      - name: Get EXSi File
        shell: powershell
        run: |
          cd $env:WORK_DIR\
          .\ESXi-Customizer-PS.ps1 -izip ..\ESXi670-201912001.zip -vft -load ${{ github.event.inputs.driver }} -ipname ${{ github.event.inputs.tag }} -outDir ..\
          cd ..
          ls
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN }}
          name: ${{ github.event.inputs.tag }}
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            ${{ github.event.inputs.tag }}.iso
